server:
  port: 8080

spring:
  application:
    name: JamesSystem
  
  datasource:
    url: jdbc:mysql://39.107.122.158:3306/james?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root          
    password: James2025!Root  
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml